#!/bin/sh

adduser counter --system
touch /tmp/currentCount.out
#chown counter:counter /tmp/currentCount.outas
chmod a+w /tmp/currentCount.out
chmod a+x /usr/bin/counter.py
chmod a+x /lib/systemd/system/
systemctl daemon-reload
service counter start



