#!/bin/sh

LOCATION=/usr/local/mypl/mypl-jar-with-dependencies.jar

echo "alias mypl='java -jar $LOCATION' " >> /etc/bash.bashrc
chmod +x $LOCATION
echo "MyPL installed at $LOCATION. Please re-start your terminal to use the compiler. 

usage:
mypl example.mypl
"
